{include file='header.tpl'}

<H1>Asian Credit Union Network Management Platform (CUNM)</H1>

<h2 style="color: #00b0f0;">PURPOSE:</h2>

<p>The adoption of effective know-your-members system is an essential part of risk management practices.  Inadequate information on the performance of an individual credit union and the overall credit union network may be subject to significant risks, especially on reputational risk.</p>

<p>CUNM seeks to maintain a real-time database of credit unions’ market sourced from more than 23,000 financial cooperatives in at least 25 countries in Asia. From individual credit union to their respective regulators, our member organizations use this information to gain a comprehensive view of Asian financial cooperatives’ market and its performance. CUNM ensures that secondary credit union organizations are able to manage the performance of their network using the information generated by the platform.  Thus, the federations are able to respond to the actual problem instead of just perceived needs.</p>

<p>Enabling the secondary level financial cooperative organizations and ACCU, as the regional organization know and analyze the performance of the network does not only contribute to the overall safety and soundness, they also protect the integrity of the financial cooperative system.</p>

<p>CUNM attempts to provide consolidated information on both select qualitative and quantitative information from the Financial Statements of Asian credit unions. Analysis derived from CUNM serve as warning signs on the current or looming threat to safety and soundness and reputational risks presented to the network.</p>

<p>The participation of the federations of credit unions is critical in meeting the desired outcome of CUNM.</p>


<h2 style="color: #00b0f0;">HOW CUNM WORKS:</h2>

<h3>User Groups</h3>

<p>CUNM has 4 user groups. Each user group has different permission and
function. The user groups in the program follow:</p>

<ol>
    <li>ACCU – Super Administrator (Group 1) <p>ACCU acts as a super administrator with rights and permission to perform all functions in the program. ACCU has an ability to create new username and password for federation (Administrator) and others (Report Viewer – User Group 4), and an ability to view the report at all levels (credit union/cooperative, federation, and all networks)</p></li>
    <li>Federation – Administrator (Group 2) <p>The Federation acts as an administrator of the program (in country) with an ability to create new username and password for it members (primary credit union/cooperative) as a user (Group 3). Federation also has an ability to monitor the data and information from the users in their network. If they would like to view the data and information of other federation, they will be treated as Report Viewer (User Group 4)</p></li>
    <li>Primary Credit Union/Cooperative – User (Group 3) <p>The primary credit union/cooperative is the user in the program who enters the data and information to the database based on their actual information and data on a monthly basis.</p></li>
    <li>Others – Report Viewer (Group 4) <p>The report viewer user group can only view the report from ACCU and Federation levels only. This user group does not have any permission to edit the report (read-only permission).</p></li>
</ol>

<h3>CUNM User Diagram:</h3>
<p>Based on the details and permission of each user group above, the diagram of the platform based on each user’s permission is illustrated below:</p>

<IMG SRC="http://{$smarty.server.HTTP_HOST}{$smarty.const.APP_PATH}/images/chart.png">

<h3>Platform</h3>
<p>The platform is a web-based platform that allows all the users be able to access the data and information store in the database of the platform from anywhere using the Internet connection. </p>

<h3>Information Gathered</h3>
<p>The program is a network information database, which contains data and information from the primary credit union/cooperative on the following components;</p>
<ul>
    <li>General information of the primary credit union/cooperative</li>
    <li>Member ranges and segmentation</li>
    <li>Individual members based on Income, Age, and Gender</li>
    <li>Have less members Services (Members with less than 100USD income per month)</li>
    <li>Classification of credit union based on assets</li>
    <li>Business distribution (Usage of service)</li>
</ul>

<h3>Reporting</h3>
<p>The reporting periods for the data and information gathered in the program shall be on monthly, quarterly and annually basis. The reporting basis are Individual Report, which is the report generated from data entering in each period, monthly, quarterly and annually, and Comparison Report, which is the report generated to compare the data from different period of time, month to month, quarter to quarter, and annual to annual.</p>

<h2 style="color: #00b0f0;">RULES & REGULATION:</h2>

<h3>Data Record Timeframe</h3>

<p>The data will be recorded on a monthly basis with set due date. Each Primary Credit Union/Cooperative User, PCU, shall enter their data and information into a template provided in the platform. The Federation Administrative User, FAU, and ACCU Administrative User, AAU, can log-into the platform to see whether the data has been entered and corrected or not from the website.
</p>
<p>ACCU and federation do not have the right to edit the data entered by the primary credit union/cooperative, but can notify them to review and amend the data and/or information in case it is not tally or same with the report submitted to the federation and/or ACCU or have any irregularities. This is to create cross-reference check in the platform.</p>

<h3>Data Maintenance</h3>

<p>The General Information of each user shall be recorded to the network to identify each user. The data entered by the credit union/cooperative will be maintained for 3 years such as 2012 to 2014 as diagram below:</p>
<ul>
    <li>2012 Data: Maintain in the database as a backup</li>
    <li>2013 Data: Maintain in the database for comparison</li>
    <li>2014 Data: Maintain in the database for comparison</li>
</ul>

<p>The database uses for comparison will be 2 years only (year-to-year comparison). Once the January 2015 Data has been entered, January 2012 data shall be deleted from the program. Hence, the database will maintain data for 36 months only at all time.</p>

{include file='footer.tpl'}