{include file='header.tpl'}

<STYLE TYPE="text/css">
	<!--
		@page { margin-right: 0.92in; margin-top: 0.96in; margin-bottom: 0.19in }
		P { margin-left: 0.08in; text-indent: -0.25in; margin-top: 0.02in; margin-bottom: 0in; font-family: "Times New Roman", serif; font-size: 11pt }
		H1 { margin-left: 0.08in; margin-top: 0in; margin-bottom: 0in; font-family: "Times New Roman", serif; font-size: 14pt; page-break-after: auto }
		H2 { margin-left: 0.08in; margin-top: 0in; margin-bottom: 0in; font-family: "Times New Roman", serif; font-size: 11pt; page-break-after: auto }
	-->
	</STYLE>

<H1 STYLE="margin-left: 0.78in; margin-top: 0.04in; line-height: 100%">
Asian Credit Union Network Management Platform (CUNM)</H1>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.18in">
<BR>
</P>
<P STYLE="margin-left: 0.08in; text-indent: 0in; margin-top: 0in; line-height: 100%"><A NAME="Purpose:"></A>
<FONT FACE="Times New Roman, serif"><FONT SIZE=3><FONT COLOR="#00b0f0"><FONT SIZE=4><B>PURP</B></FONT></FONT><FONT COLOR="#00b0f0"><FONT SIZE=4><B>OSE:</B></FONT></FONT></FONT></FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.18in">
<BR>
</P>
<P STYLE="margin-left: 0.08in; margin-right: 0.25in; text-indent: 0in; margin-top: 0in; line-height: 100%"><A NAME="The adoption of effective know-your-members system is an essential part of risk management practices.  Inadequate information on the performance of an individual credit union and the overall credit union network may be subject to significant risks, es..."></A>
<FONT FACE="Times New Roman, serif"><FONT SIZE=3>The adoption of
effective know-your-members system is an essential part of risk
management practices.  Inadequate information on the performance of
an individual credit union and the overall credit union network may
be subject to significant risks, especially on reputational risk.</FONT></FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.18in">
<BR>
</P>
<P STYLE="margin-left: 0.08in; margin-right: 0.23in; text-indent: 0in; margin-top: 0in; line-height: 100%"><A NAME="CUNM seeks to maintain a real-time database of credit unions&rsquo; market sourced from more than 23,000 financial cooperatives in at least 25 countries in Asia. From individual credit union to their respective regulators, our member organizations use this ..."></A>
<FONT FACE="Times New Roman, serif"><FONT SIZE=3>CUNM seeks to
maintain a real-time database of credit unions&rsquo; market sourced
from more than 23,000 financial cooperatives in at least 25 countries
in Asia. From individual credit union to their respective regulators,
our member organizations use this information to gain a comprehensive
view of Asian financial cooperatives&rsquo; market and its
performance. CUNM ensures that secondary credit union organizations
are able to manage the performance of their network using the
information generated by the platform. Thus, the federations are able
to respond to the actual problem instead of just perceived needs.</FONT></FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.18in">
<BR>
</P>
<P STYLE="margin-left: 0.08in; margin-right: 0.22in; text-indent: 0in; margin-top: 0in; line-height: 100%"><A NAME="Enabling the secondary level financial cooperative organizations and ACCU, as the regional organization know and analyze the performance of the network does not only contribute to the overall safety and soundness, they also protect the integrity of th..."></A>
<FONT FACE="Times New Roman, serif"><FONT SIZE=3>Enabling the
secondary level financial cooperative organizations and ACCU, as the
regional organization know and analyze the performance of the network
does not only contribute to the overall safety and soundness, they
also protect the integrity of the financial cooperative system.</FONT></FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.18in">
<BR>
</P>
<P STYLE="margin-left: 0.08in; margin-right: 0.12in; text-indent: 0in; margin-top: 0in; line-height: 100%"><A NAME="CUNM attempts to provide consolidated information on both select qualitative and quantitative information from the Financial Statements of Asian credit unions. Analysis derived from CUNM serve as warning signs on the current or looming threat to safet..."></A>
<FONT FACE="Times New Roman, serif"><FONT SIZE=3>CUNM attempts to
provide consolidated information on both select qualitative and
quantitative information from the Financial Statements of Asian
credit unions. Analysis derived from CUNM serve as warning signs on
the current or looming threat to safety and soundness and
reputational risks presented to the network.</FONT></FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.18in">
<BR>
</P>
<P STYLE="margin-left: 0.08in; text-indent: 0in; margin-top: 0in; line-height: 100%"><A NAME="The participation of the federations of credit unions is critical in meeting the desired outcome of CUNM."></A>
<FONT FACE="Times New Roman, serif"><FONT SIZE=3>The participation of
the federations of credit unions is critical in meeting the desired
outcome of CUNM.</FONT></FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0in; line-height: 0.19in">
<BR>
</P>
<P STYLE="margin-left: 0.08in; text-indent: 0in; margin-top: 0in; line-height: 100%"><A NAME="How CUNM Works:"></A>
<FONT FACE="Times New Roman, serif"><FONT SIZE=3><FONT COLOR="#00b0f0"><FONT SIZE=4><B>HOW
</B></FONT></FONT><FONT COLOR="#00b0f0"><FONT SIZE=4><B>CUN</B></FONT></FONT><FONT COLOR="#00b0f0"><FONT SIZE=4><B>M</B></FONT></FONT><FONT COLOR="#00b0f0"><FONT SIZE=4><B>
</B></FONT></FONT><FONT COLOR="#00b0f0"><FONT SIZE=4><B>WO</B></FONT></FONT><FONT COLOR="#00b0f0"><FONT SIZE=4><B>R</B></FONT></FONT><FONT COLOR="#00b0f0"><FONT SIZE=4><B>KS:</B></FONT></FONT></FONT></FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.19in">
<BR>
</P>
<H2 STYLE="line-height: 100%">User Groups</H2>
<P STYLE="margin-right: 0.08in; text-indent: 0in; margin-top: 0.02in; line-height: 114%">
CUNM has 4 user groups. Each user group has different permission and
function. The user groups in the program follow:</P>
<OL>
	<LI><H2 STYLE="margin-top: 0in; line-height: 100%">ACCU &ndash;
	Super Administrator (Group 1)</H2>
</OL>
<P ALIGN=JUSTIFY STYLE="margin-left: 0.58in; margin-right: 0.08in; text-indent: 0in; line-height: 115%">
ACCU acts as a super administrator with rights and permission to
perform all functions in the program. ACCU has an ability to create
new username and password for federation (Administrator) and others
(Report Viewer &ndash; User Group 4), and an ability to view the
report at all levels (credit union/cooperative, federation, and all
networks)</P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.19in">
<BR>
</P>
<OL START=2>
	<LI><H2 STYLE="line-height: 100%">Federation &ndash; Administrator
	(Group 2)</H2>
</OL>
<P ALIGN=JUSTIFY STYLE="margin-left: 0.58in; margin-right: 0.08in; text-indent: 0in; margin-top: 0.02in; line-height: 114%">
The Federation acts as an administrator of the program (in country)
with an ability to create new username and password for it members
(primary credit union/cooperative) as a user (Group 3). Federation
also has an ability to monitor the data and information from the
users in their network. If they would like to view the data and
information of other federation, they will be treated as Report
Viewer (User Group 4)</P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0in; line-height: 0.12in; page-break-before: always">
<BR>
</P>
<OL START=3>
	<LI><H2 STYLE="margin-top: 0.05in; line-height: 100%">Primary Credit
	Union/Cooperative &ndash; User (Group 3)</H2>
</OL>
<P STYLE="margin-left: 0.58in; text-indent: 0in; line-height: 115%">The
 primary  credit  union/cooperative  is  the  user  in  the  program 
who  enters  the  data  and information to the database based on
their actual information and data on a monthly basis.</P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.19in">
<BR>
</P>
<OL START=4>
	<LI><H2 STYLE="line-height: 100%">Others &ndash; Report Viewer
	(Group 4)</H2>
</OL>
<P STYLE="margin-left: 0.58in; text-indent: 0in; line-height: 115%">The
report viewer user group can only view the report from ACCU and
Federation levels only. This user group does not have any permission
to edit the report (read-only permission).</P>
<P STYLE="text-indent: 0in; margin-top: 0in; line-height: 0.18in"><FONT COLOR="#ff0000">**</FONT><FONT COLOR="#ff0000">I</FONT><FONT COLOR="#ff0000">n</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">m</FONT><FONT COLOR="#ff0000">y</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">op</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">n</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">on,</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">he</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">n</FONT><FONT COLOR="#ff0000">f</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">m</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">ti</FONT><FONT COLOR="#ff0000">on</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">on</FONT><FONT COLOR="#ff0000"> </FONT><FONT COLOR="#ff0000">Us</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">Gr</FONT><FONT COLOR="#ff0000">oups</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">sh</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">be</FONT><FONT COLOR="#ff0000"> </FONT><FONT COLOR="#ff0000">s</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">ed</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">n</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">he</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">M</FONT><FONT COLOR="#ff0000">anu</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">ns</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">ad</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">f</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">he</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">Da</FONT><FONT COLOR="#ff0000">s</FONT><FONT COLOR="#ff0000">hbo</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">rd</FONT></P>
<P STYLE="text-indent: 0in; margin-top: 0.03in; line-height: 100%"><FONT COLOR="#ff0000">pane</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">.</FONT><FONT COLOR="#000000">**</FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0in; line-height: 0.09in">
<BR>
</P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0in; line-height: 0.14in">
<BR>
</P>
<H2 STYLE="line-height: 100%">ACNDM User Diagram</H2>
<P STYLE="margin-right: 0.08in; text-indent: 0in; margin-top: 0.02in; line-height: 114%">
Based on the details and permission of each user group above, the
diagram of the platform based on each user&rsquo;s permission is
illustrated below:</P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0in; line-height: 0.07in">
<BR>
</P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0in; line-height: 0.14in">
<BR>
</P>
<P STYLE="margin-left: 0.09in; text-indent: 0in; margin-top: 0in; line-height: 100%">
<IMG SRC="/images/chart.png" NAME="graphics1" ALIGN=BOTTOM WIDTH=605 HEIGHT=228 BORDER=0></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.19in">
<BR>
</P>
<H2 STYLE="line-height: 100%">Platform</H2>
<P STYLE="margin-left: 0.08in; margin-right: 0.08in; text-indent: 0in; line-height: 114%">
The program shall be integrated to one website for easy data and
information access by the users from anywhere. The maintenance will
be only 1 database for User Group 1, 2 and 3.</P>
<P STYLE="margin-right: 0.08in; text-indent: 0in; margin-top: 0in; line-height: 114%">
<FONT COLOR="#ff0000">T</FONT><FONT COLOR="#ff0000">he</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">p</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">f</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">rm</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">s</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000"> </FONT><FONT COLOR="#ff0000">web</FONT><FONT COLOR="#ff0000">-</FONT><FONT COLOR="#ff0000">based</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">p</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">f</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">rm</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">hat</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">ows</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">he</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">us</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">rs</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">be</FONT><FONT COLOR="#ff0000"> </FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">b</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">c</FONT><FONT COLOR="#ff0000">ce</FONT><FONT COLOR="#ff0000">s</FONT><FONT COLOR="#ff0000">s</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">he</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">da</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">and</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">nf</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">m</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">ti</FONT><FONT COLOR="#ff0000">on
s</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">e
</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">n </FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">h</FONT><FONT COLOR="#ff0000">e
d</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">b</FONT><FONT COLOR="#ff0000">ase
</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">f</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">he</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">p</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">f</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">rm</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">from</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">an</FONT><FONT COLOR="#ff0000">y</FONT><FONT COLOR="#ff0000">w</FONT><FONT COLOR="#ff0000">here
u</FONT><FONT COLOR="#ff0000">s</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">ng</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">he
</FONT><FONT COLOR="#ff0000">I</FONT><FONT COLOR="#ff0000">n</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">ern</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">c</FONT><FONT COLOR="#ff0000">onne</FONT><FONT COLOR="#ff0000">c</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">on.</FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.19in">
<BR>
</P>
<H2 STYLE="line-height: 100%">Information Gathered</H2>
<P STYLE="margin-right: 0.08in; text-indent: 0in; margin-top: 0.02in; line-height: 114%">
The program is a network information database which contains data and
information from the primary credit union/cooperative on the
following components;</P>
<UL>
	<LI><P STYLE="text-indent: 0in; margin-top: 0.01in; line-height: 100%">
	General information of the primary credit union/cooperative</P>
	<LI><P STYLE="text-indent: 0in; margin-top: 0.04in; line-height: 100%">
	Member ranges and segmentation</P>
	<LI><P STYLE="text-indent: 0in; margin-top: 0.04in; line-height: 100%">
	Individual members based on Income, Age, and Gender</P>
	<LI><P STYLE="text-indent: 0in; margin-top: 0.03in; line-height: 100%">
	Have less members Services (Members with less than 100USD income per
	month)</P>
	<LI><P STYLE="text-indent: 0in; margin-top: 0.04in; line-height: 100%">
	Classification of credit union based on assets</P>
	<LI><P STYLE="text-indent: 0in; margin-top: 0.04in; line-height: 100%">
	Business distribution (Usage of service)</P>
</UL>
<P STYLE="margin-left: 0.08in; margin-right: 0.08in; text-indent: 0in; margin-top: 0.05in; line-height: 114%; page-break-before: always">
<FONT FACE="Times New Roman, serif"><FONT SIZE=3><FONT SIZE=2 STYLE="font-size: 11pt">For</FONT><FONT SIZE=2 STYLE="font-size: 11pt">
</FONT><FONT SIZE=2 STYLE="font-size: 11pt">m</FONT><FONT SIZE=2 STYLE="font-size: 11pt">ore
</FONT><FONT SIZE=2 STYLE="font-size: 11pt">i</FONT><FONT SIZE=2 STYLE="font-size: 11pt">n</FONT><FONT SIZE=2 STYLE="font-size: 11pt">f</FONT><FONT SIZE=2 STYLE="font-size: 11pt">or</FONT><FONT SIZE=2 STYLE="font-size: 11pt">m</FONT><FONT SIZE=2 STYLE="font-size: 11pt">a</FONT><FONT SIZE=2 STYLE="font-size: 11pt">ti</FONT><FONT SIZE=2 STYLE="font-size: 11pt">on
and </FONT><FONT SIZE=2 STYLE="font-size: 11pt">d</FONT><FONT SIZE=2 STYLE="font-size: 11pt">e</FONT><FONT SIZE=2 STYLE="font-size: 11pt">t</FONT><FONT SIZE=2 STYLE="font-size: 11pt">a</FONT><FONT SIZE=2 STYLE="font-size: 11pt">i</FONT><FONT SIZE=2 STYLE="font-size: 11pt">l</FONT><FONT SIZE=2 STYLE="font-size: 11pt">s</FONT><FONT SIZE=2 STYLE="font-size: 11pt">
</FONT><FONT SIZE=2 STYLE="font-size: 11pt">o</FONT><FONT SIZE=2 STYLE="font-size: 11pt">f</FONT><FONT SIZE=2 STYLE="font-size: 11pt">
</FONT><FONT SIZE=2 STYLE="font-size: 11pt">d</FONT><FONT SIZE=2 STYLE="font-size: 11pt">a</FONT><FONT SIZE=2 STYLE="font-size: 11pt">t</FONT><FONT SIZE=2 STYLE="font-size: 11pt">a
</FONT><FONT SIZE=2 STYLE="font-size: 11pt">t</FONT><FONT SIZE=2 STYLE="font-size: 11pt">o</FONT><FONT SIZE=2 STYLE="font-size: 11pt">
</FONT><FONT SIZE=2 STYLE="font-size: 11pt">be </FONT><FONT SIZE=2 STYLE="font-size: 11pt">g</FONT><FONT SIZE=2 STYLE="font-size: 11pt">a</FONT><FONT SIZE=2 STYLE="font-size: 11pt">t</FONT><FONT SIZE=2 STYLE="font-size: 11pt">h</FONT><FONT SIZE=2 STYLE="font-size: 11pt">e</FONT><FONT SIZE=2 STYLE="font-size: 11pt">red
und</FONT><FONT SIZE=2 STYLE="font-size: 11pt">e</FONT><FONT SIZE=2 STYLE="font-size: 11pt">r</FONT><FONT SIZE=2 STYLE="font-size: 11pt">
</FONT><FONT SIZE=2 STYLE="font-size: 11pt">each co</FONT><FONT SIZE=2 STYLE="font-size: 11pt">m</FONT><FONT SIZE=2 STYLE="font-size: 11pt">ponen</FONT><FONT SIZE=2 STYLE="font-size: 11pt">t</FONT><FONT SIZE=2 STYLE="font-size: 11pt">,
</FONT><FONT SIZE=2 STYLE="font-size: 11pt">p</FONT><FONT SIZE=2 STYLE="font-size: 11pt">l</FONT><FONT SIZE=2 STYLE="font-size: 11pt">e</FONT><FONT SIZE=2 STYLE="font-size: 11pt">ase
r</FONT><FONT SIZE=2 STYLE="font-size: 11pt">e</FONT><FONT SIZE=2 STYLE="font-size: 11pt">fer</FONT><FONT SIZE=2 STYLE="font-size: 11pt">
</FONT><FONT SIZE=2 STYLE="font-size: 11pt">t</FONT><FONT SIZE=2 STYLE="font-size: 11pt">o
</FONT><FONT SIZE=2 STYLE="font-size: 11pt">t</FONT><FONT SIZE=2 STYLE="font-size: 11pt">he</FONT><FONT SIZE=2 STYLE="font-size: 11pt">
</FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>Fo</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>r</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>m</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>at</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><B>
</B></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>for CU</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>
N</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>e</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>t</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>w</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>o</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>rk
</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>M</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>anag</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>e</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>m</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>ent</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>
</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>D</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>B.x</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt"><I><U><B>ls</B></U></I></FONT><FONT SIZE=2 STYLE="font-size: 11pt">.</FONT></FONT></FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0in; line-height: 0.15in">
<BR>
</P>
<H2 ALIGN=JUSTIFY STYLE="margin-right: 5.92in; margin-top: 0.05in; line-height: 100%">
Reporting</H2>
<P ALIGN=JUSTIFY STYLE="margin-right: 0.08in; text-indent: 0in; line-height: 115%">
The reporting periods for the data and information gathered in the
program shall be on monthly, quarterly and annually basis. <FONT COLOR="#ff0000">T</FONT><FONT COLOR="#ff0000">he</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">por</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">ng</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">ba</FONT><FONT COLOR="#ff0000">s</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">s</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">I</FONT><FONT COLOR="#ff0000">nd</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">v</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">du</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">Rep</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">,</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">wh</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">ch</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">s</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">he</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">ep</FONT><FONT COLOR="#ff0000">ort</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">g</FONT><FONT COLOR="#ff0000">ener</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">ed</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">f</FONT><FONT COLOR="#ff0000">rom</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">da</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">a
en</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">ng</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">n</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">each</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">pe</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">od,</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">m</FONT><FONT COLOR="#ff0000">on</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">h</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">y</FONT><FONT COLOR="#ff0000">,</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">quar</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">y</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">and</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">ann</FONT><FONT COLOR="#ff0000">u</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">ll</FONT><FONT COLOR="#ff0000">y</FONT><FONT COLOR="#ff0000">,</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">and</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">Co</FONT><FONT COLOR="#ff0000">m</FONT><FONT COLOR="#ff0000">par</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">son</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">Re</FONT><FONT COLOR="#ff0000">p</FONT><FONT COLOR="#ff0000">or</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">,</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">w</FONT><FONT COLOR="#ff0000">h</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">ch</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">s</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">he</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">ep</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">t
</FONT><FONT COLOR="#ff0000">g</FONT><FONT COLOR="#ff0000">enera</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">ed</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">co</FONT><FONT COLOR="#ff0000">m</FONT><FONT COLOR="#ff0000">pare</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">h</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">da</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">from</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">d</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">f</FONT><FONT COLOR="#ff0000">fe</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">ent</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">p</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">od</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">of</FONT><FONT COLOR="#ff0000"> </FONT><FONT COLOR="#ff0000">ti</FONT><FONT COLOR="#ff0000">m</FONT><FONT COLOR="#ff0000">e,</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">m</FONT><FONT COLOR="#ff0000">on</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">h</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">m</FONT><FONT COLOR="#ff0000">on</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">h,</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">qua</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">er</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">qu</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">er,</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">an</FONT><FONT COLOR="#ff0000">d annu</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">
t</FONT><FONT COLOR="#ff0000">o</FONT><FONT COLOR="#ff0000"> </FONT><FONT COLOR="#ff0000">ann</FONT><FONT COLOR="#ff0000">u</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">.</FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.19in">
<BR>
</P>
<H1 ALIGN=JUSTIFY STYLE="margin-right: 4.28in; line-height: 100%"><A NAME="RULES &amp; REGULATION:"></A>
<FONT COLOR="#00b0f0">RU</FONT><FONT COLOR="#00b0f0">LES &amp;</FONT><FONT COLOR="#00b0f0">
R</FONT><FONT COLOR="#00b0f0">EG</FONT><FONT COLOR="#00b0f0">U</FONT><FONT COLOR="#00b0f0">L</FONT><FONT COLOR="#00b0f0">A</FONT><FONT COLOR="#00b0f0">T</FONT><FONT COLOR="#00b0f0">I</FONT><FONT COLOR="#00b0f0">O</FONT><FONT COLOR="#00b0f0">N:</FONT></H1>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.19in">
<BR>
</P>
<H2 ALIGN=JUSTIFY STYLE="margin-right: 4.99in; line-height: 100%">Data
Record Timeframe</H2>
<P ALIGN=JUSTIFY STYLE="margin-right: 0.08in; text-indent: 0in; margin-top: 0.02in; line-height: 114%">
The data will be recorded on a monthly basis with set due date. Each
Primary Credit Union/Cooperative User, PCU, shall enter their data
and information into a template provided in the platform. The
Federation Administrative User, FAU, and ACCU Administrative User,
AAU, can log-into the platform to see whether the data has been
entered and corrected or not from the website.</P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.19in">
<BR>
</P>
<P ALIGN=JUSTIFY STYLE="margin-right: 0.08in; text-indent: 0in; margin-top: 0in; line-height: 114%">
ACCU and federation do not have the right to edit the data entered by
the primary credit union/cooperative, but can notify them to review
and amend the data and/or information in case it is not tally or same
with the report submitted to the federation and/or ACCU <FONT COLOR="#ff0000">or</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">ha</FONT><FONT COLOR="#ff0000">v</FONT><FONT COLOR="#ff0000">e</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">ny</FONT><FONT COLOR="#ff0000">
</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">rre</FONT><FONT COLOR="#ff0000">g</FONT><FONT COLOR="#ff0000">u</FONT><FONT COLOR="#ff0000">l</FONT><FONT COLOR="#ff0000">a</FONT><FONT COLOR="#ff0000">r</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">t</FONT><FONT COLOR="#ff0000">i</FONT><FONT COLOR="#ff0000">es</FONT><FONT COLOR="#000000">.</FONT><FONT COLOR="#000000">
</FONT><FONT COLOR="#000000">T</FONT><FONT COLOR="#000000">h</FONT><FONT COLOR="#000000">i</FONT><FONT COLOR="#000000">s</FONT><FONT COLOR="#000000">
</FONT><FONT COLOR="#000000">i</FONT><FONT COLOR="#000000">s </FONT><FONT COLOR="#000000">t</FONT><FONT COLOR="#000000">o
</FONT><FONT COLOR="#000000">c</FONT><FONT COLOR="#000000">re</FONT><FONT COLOR="#000000">a</FONT><FONT COLOR="#000000">t</FONT><FONT COLOR="#000000">e
</FONT><FONT COLOR="#000000">c</FONT><FONT COLOR="#000000">ro</FONT><FONT COLOR="#000000">s</FONT><FONT COLOR="#000000">s</FONT><FONT COLOR="#000000">-</FONT><FONT COLOR="#000000">refe</FONT><FONT COLOR="#000000">r</FONT><FONT COLOR="#000000">ence</FONT><FONT COLOR="#000000">
</FONT><FONT COLOR="#000000">c</FONT><FONT COLOR="#000000">h</FONT><FONT COLOR="#000000">eck</FONT><FONT COLOR="#000000">
</FONT><FONT COLOR="#000000">i</FONT><FONT COLOR="#000000">n </FONT><FONT COLOR="#000000">t</FONT><FONT COLOR="#000000">h</FONT><FONT COLOR="#000000">e
p</FONT><FONT COLOR="#000000">l</FONT><FONT COLOR="#000000">a</FONT><FONT COLOR="#000000">t</FONT><FONT COLOR="#000000">for</FONT><FONT COLOR="#000000">m</FONT><FONT COLOR="#000000">.</FONT></P>
<P STYLE="margin-left: 0in; text-indent: 0in; margin-top: 0.01in; line-height: 0.19in">
<BR>
</P>
<H2 ALIGN=JUSTIFY STYLE="margin-left: 0.08in; margin-right: 5.38in; line-height: 100%">
Data Maintenance</H2>
<P ALIGN=JUSTIFY STYLE="margin-right: 0.08in; text-indent: 0in; line-height: 115%">
The General Information of each user shall be recorded to the network
to identify each user. The data entered by the credit
union/cooperative will be maintained for 3 years such as 2012 to 2014
as diagram below:</P>
<UL>
	<LI><P ALIGN=JUSTIFY STYLE="margin-right: 3.51in; text-indent: 0in; margin-top: 0in; line-height: 100%">
	<I><B>2012 </B></I><I><B>D</B></I><I><B>a</B></I><I><B>t</B></I><I><B>a</B></I>:
	Maintain in the database as a backup</P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-right: 3.3in; text-indent: 0in; margin-top: 0.03in; line-height: 100%">
	<I><B>2013 </B></I><I><B>D</B></I><I><B>a</B></I><I><B>t</B></I><I><B>a</B></I>:
	Maintain in the database for comparison</P>
	<LI><P ALIGN=JUSTIFY STYLE="margin-right: 3.3in; text-indent: 0in; margin-top: 0.03in; line-height: 100%">
	<I><B>2014 </B></I><I><B>D</B></I><I><B>a</B></I><I><B>t</B></I><I><B>a</B></I>:
	Maintain in the database for comparison</P>
</UL>
<P ALIGN=JUSTIFY STYLE="margin-right: 0.08in; text-indent: 0in; margin-top: 0.03in; line-height: 115%">
The database uses for comparison will be 2 years only (year-to-year
comparison). Once the January 2015 Data has been entered, January
2012 data shall be deleted from the program. Hence, the database will
maintain data for 36 months only at all time.</P>

{include file='footer.tpl'}